#!/usr/bin/env bash
# Install Nginx
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
ufwnallow 'Nginx HTTP'
echo  "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
