#!/usr/bin/env bash
# script that pings an IP address passed as an argument

# Ip variable
ip="${1}"

# file name
file=$(basename "${BASH_SOURCE[@]}")

if ! [ "$ip" ]; then
	echo "Usage: ${file} {IP_ADDRESS}"
else
	ping -c 5 "${ip}"
fi
