#!/bin/bash
# Use the 'ps' command with appropriate options to display the processes
# shellcheck disable=SC2009
# -e: Select all processes
# -o: Custom output format
# --forest: Show process hierarchy
# USER, PID, %CPU, %MEM, VSZ, RSS, TTY, STAT, START, TIME, COMMAND

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest | grep bash
