#!/usr/bin/env bash
# To infinity and beyond indefinitely and I am invincible!!! when receiving a SIGTERM signal

function sigterm_handler() {
	echo "I am invincible!!!"
}
trap sigterm_handler SIGTERM

while true;do
	echo "To infinity and beyond"
	sleep 2
done
