#!/usr/bin/env bash
# Using a for loop to iterate from 1 to 100

for ((number=1; number<=100; number++))
do
    # Check for multiples of both 3 and 5 (FizzBuzz)
    if ((number % 3 == 0)) && ((number % 5 == 0))
    then
        echo "FizzBuzz"
    # Check for multiples of 3 (Fizz)
    elif ((number % 3 == 0))
    then
        echo "Fizz"
    # Check for multiples of 5 (Buzz)
    elif ((number % 5 == 0))
    then
        echo "Buzz"
    # Display the number if none of the above conditions are met
    else
        echo "$number"
    fi
done
