#!/usr/bin/env bash
# Displays Best school with while loop at 9th hi

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
