#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# It shows only the part of the name after the first dash

# Using the for loop to iterate through the files in the current directory
for file in *
do
    # Check if the file is not hidden and is a regular file (not a directory)
    if [ ! -d "$file" ] && [ ! "${file}" = ".*" ]
    then
        # Extract the part of the name after the first dash
        file_name="${file#*-}"
        echo "$file_name"
    fi
done
